[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
actix-multipart = "0.7.2"
actix-web = "4.9.0"
futures = "0.3.31"
wasmedge-sdk = "0.14.0"
wasmtime = "29.0.1"
wasmtime-wasi = "29.0.1"
